### ISSUE TITLE
Missing class de/leonhard/storage/Json

### ISSUE THREAD

**Issue by cryxli** [uiytt/FastGrowth#6]
# Observation

Game does not start producing a crash report due to a missing dependency in FastGrowth. See below.

# Setup

- Minecraft 1.18.2
- Fabric Loader 0.13.3
- Fabric API 0.48.0 1.18.2
- FastGrowth 1.6

Simply starting the client will produce a [crash-2022-04-08_17.21.20-client.txt](https://github.com/uiytt/FastGrowth/files/8453333/crash-2022-04-08_17.21.20-client.txt)

# Suggestion

1. Embed the dependencies in the build (e.g. shadow maven plugin)
2. Use a lib for processing JSON that is already present with the MC setup

Thanks for all the effort you put in the plugin! Hope this helps to sort things out.

Cheers,
cryxli

**Comment by uiytt** [comment]
I'm sorry that I didn't notice this issue request earlier :/ 
Anyway it should be fixed in FastGrowth 1.6.1, will put it online
